export const Products = [
  {
    id: 'mobilisco',
    page: '/mobilisco',
    title: 'Mobilisco',
    formUrl: 'https://docs.google.com/forms/d/1NmOvwDBvewcF_F68_tsugW_jv_4_5aX98mVk-bajzdY/formResponse?entry.162101201=',
    downloadUrl: 'MOBILISCO V5.7.1.zip',
    tagline: 'Les voyages scolaires cessent d’être un enfer',
    description: 'Un logiciel de gestion de vos voyages scolaires, depuis l’inscription des élèves jusqu’au bilan financier',
    imageSource: 'static/arrow.png',
    color: '#24b47e',
    background: '',
  },
  {
    id: 'bourse',
    page: 'bourse',
    title: 'Bourse',
    tagline: 'Vos demandes de bourses sans papier',
    description: 'Bourse est un outil de demande en ligne de bourse de collège, pour le bonheur des intendants comme des parents',
    imageSource: 'static/hat.png',
    color: '#29adad',
    background: '',
    downloadLink: {
      label: 'bourse.beta.gouv.fr',
      href: 'https://bourse.beta.gouv.fr',
    },
  },
  {
    id: 'cogefi',
    page: 'cogefi',
    title: 'Cogefi',
    formUrl: 'https://docs.google.com/forms/d/1Fsf8ITt2ZTjPmxx43h6kQvIfaLqnK-JoLBY8EkaelXw/formResponse?entry.551798432=',
    downloadUrl: 'COGEFI V17.08- XXXXX(remplacer xxxx par le nom étab).zip',
    tagline: 'Le logiciel d’analyse financière',
    description: 'Cogefi permet la production rapide et automatique de rapports financiers pour les collèges et lycées',
    imageSource: 'static/graph.png',
    color: '#fb2058',
    background: '',
  },
  {
    id: 'gemasco',
    page: 'gemasco',
    title: 'Gemasco',
    formUrl: 'https://docs.google.com/forms/d/1AcTYcJrqYufC7N8SUeWzC1EpID0kprPHjTNq8Z5JOuk/formResponse?entry.1936573090=',
    downloadUrl: 'GEMASCO V1.6.rar',
    tagline: 'L’appli qui gère les manuels scolaires',
    description: 'Gemasco commande, distribue, récupère et fait même l’inventaire de vos manuels scolaires !',
    imageSource: 'static/book.png',
    color: '#ff7b19',
    background: '',
  },
  {
    id: 'emaintenance',
    page: '',
    title: 'E-maintenance',
    tagline: 'Réparer n\'est plus un problème',
    description: 'L\'appli e-maintenance permet l\'entretien et la gestion de tout type de matériel au sein d\'un établissement, de l\'ampoule grillée au rétroprojecteur en panne.',
    imageSource: 'static/wrench.png',
    color: '#7dd2c2',
    background: '',
  },
  {
    id: 'votre-projet',
    page: 'votre-projet',
    title: 'Votre projet',
    tagline: 'L’open académicien, c’est vous !',
    description: 'Vous voulez moderniser votre profession ? Vous avez une idée que vous aimeriez développer et pour laquelle vous êtes prêt à vous investir ? Contactez-nous ! On vous attendait',
    imageSource: 'static/lamp.png',
    color: '#ffd966',
    background: 'static/votre-projet.jpg',
  }
]

export const Colors = {
  primary: '#26a69a',
}
