export const Products = [
  {
    id: 'mobilisco',
    page: '/mobilisco',
    title: 'Mobilisco',
    formUrl: 'https://docs.google.com/forms/d/1NmOvwDBvewcF_F68_tsugW_jv_4_5aX98mVk-bajzdY/formResponse?entry.162101201=',
    downloadUrl: 'static/files/MOBILISCO V5.7.1.zip',
    tagline: 'Les voyages scolaires cessent d’être un enfer',
    description: 'Un logiciel de gestion de vos voyages scolaires, depuis l’inscription des élèves jusqu’au bilan financier',
    imageSource: 'static/arrow.png',
    color: '#24b47e',
    background: '',
    salesPoints: [
      'Inscription des élèves aux voyages et édition des lettres d\'engagement des familles',
      'Edition des budgets, bilan financier, justificatif des ordres de recettes et documents en tout genre',
      'Suivi des encaissements sur un document unique',
    ],
    externalLinks: [
      {
        icon: 'static/icon-forum.png',
        label: 'Forum',
        href: 'http://gestionnaires.actifforum.com/f23-openacademie-et-ses-outils',
      },
      {
        icon: 'static/icon-video.png',
        label: 'Tutoriels',
        href: 'https://www.youtube.com/watch?v=OTHWhZy9oQs&t=2s',
      },
    ],
  },
  {
    id: 'bourse',
    page: 'bourse',
    title: 'Bourse',
    tagline: 'Vos demandes de bourses sans papier',
    description: 'Bourse est un outil de demande en ligne de bourse de collège, pour le bonheur des intendants comme des parents',
    imageSource: 'static/hat.png',
    color: '#29adad',
    background: '',
    downloadLink: {
      label: 'bourse.beta.gouv.fr',
      href: 'https://bourse.beta.gouv.fr',
    },
    externalLinks: [
      {
        icon: 'static/icon-video.png',
        label: 'Tutoriel',
        href: 'https://www.youtube.com/watch?v=6FOz4E_W6I4',
      },
    ],
  },
  {
    id: 'cogefi',
    page: 'cogefi',
    title: 'Cogefi',
    formUrl: 'https://docs.google.com/forms/d/1Fsf8ITt2ZTjPmxx43h6kQvIfaLqnK-JoLBY8EkaelXw/formResponse?entry.551798432=',
    emailEntryRef: '363200688',
    pageEntryRef: '1506732456',
    downloadUrl: 'static/files/COGEFI V17.08- XXXXX(remplacer xxxx par le nom étab).zip',
    tagline: 'Le logiciel d’analyse financière',
    description: 'Cogefi permet la production rapide et automatique de rapports financiers pour les collèges et lycées',
    imageSource: 'static/graph.png',
    color: '#fb2058',
    background: '',
    externalLinks: [
      {
        icon: 'static/icon-forum.png',
        label: 'Forum',
        href: 'http://gestionnaires.actifforum.com/f23-openacademie-et-ses-outils',
      },
      {
        icon: 'static/icon-video.png',
        label: 'Tutoriels',
        href: 'http://www.dailymotion.com/espaceple',
      },
    ],
  },
  {
    id: 'gemasco',
    page: 'gemasco',
    title: 'Gemasco',
    formUrl: 'https://docs.google.com/forms/d/1AcTYcJrqYufC7N8SUeWzC1EpID0kprPHjTNq8Z5JOuk/formResponse?entry.1936573090=',
    emailEntryRef: '843103382',
    pageEntryRef: '89190430',
    downloadUrl: 'static/files/GEMASCO V1.6.rar',
    tagline: 'L’appli qui gère les manuels scolaires',
    description: 'Gemasco commande, distribue, récupère et fait même l’inventaire de vos manuels scolaires !',
    imageSource: 'static/book.png',
    color: '#ff7b19',
    background: '',
    salesPoints: [
      'Création d\'étiquettes code-barre à coller sur les manuels scolaires',
      'Prêt et retour automatisé',
      'Suivi du stock en temps réel',
      'Edition d\'avis aux familles des livres non-rendus ou dégradés',
      'Déterminer à tout moment à qui appartient n\'importe quel livre',
    ],
    externalLinks: [
      {
        icon: 'static/icon-video.png',
        label: 'Videos',
        href: 'https://www.youtube.com/watch?v=PnIVIGS52fU',
      },
    ],
  },
  {
    id: 'emaintenance',
    page: 'emaintenance',
    title: 'E-maintenance',
    tagline: 'Réparer n\'est plus un problème',
    description: 'L\'appli e-maintenance permet l\'entretien et la gestion de tout type de matériel au sein d\'un établissement, de l\'ampoule grillée au rétroprojecteur en panne.',
    imageSource: 'static/wrench.png',
    color: '#7dd2c2',
    background: '',
  },
  {
    id: 'votre-projet',
    page: 'votre-projet',
    title: 'Votre projet',
    tagline: 'L’open académicien, c’est vous !',
    description: 'Vous voulez moderniser votre profession ? Vous avez une idée que vous aimeriez développer et pour laquelle vous êtes prêt à vous investir ? Contactez-nous ! On vous attendait',
    imageSource: 'static/lamp.png',
    color: '#ffd966',
    background: 'static/votre-projet.jpg',
  }
]

export const Colors = {
  primary: '#26a69a',
}
